# docker run splunk/enterprise:7.0.3
# Options on how to review the EULA and accept it:
# 1. docker run -it splunk/enterprisetrial:7.0.3
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/enterprisetrial

# Support for Docker Compose v3, https://docs.docker.com/compose/overview/
version: '3'

services:
  splunkenterprise:
    #build: .
    hostname: splunkenterprise
    image: splunk/splunk:latest
    #image: splunk/splunk:edge
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_LICENSE_URI: Free
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    volumes:
      - ./TraceExplorationSplunk:/opt/splunk/etc/apps/TraceExplorationSplunk/

